refactor (**) update Kotlin version, refactor data class, remove warnings
Kuama-IT/android-document-scanner pull request #12
Opened 2022-07-27 09:29 UTC by giovanni-nic-kuama

2022-07-27 09:54 UTC, matteoKuama requested changes

2022-07-27 09:54 UTC, matteoKuama commented on .idea/misc.xml
> +  <component name="DesignSurface">
maybe .gitignore?

2022-07-27 09:54 UTC, matteoKuama commented on app/src/main/java/net/kuama/documentscanner/utils/PerspectiveTransformUtils.kt
> +    fun sortPoints(sourcePointsArray: Array<Point>): Array<Point> {
wouldn't be better to have a square or similar object as parameter? it can be an array with any number of fields

2022-07-27 09:54 UTC, matteoKuama commented on app/src/main/java/net/kuama/documentscanner/extensions/Context.kt
> +        val mediaDir = filesDir.let {
`filesDir?.let` need a ?
otherwise it is the same of `File(filesDir, appContext.resources.getString(R.string.app_name)).apply { mkdirs() }`

2022-07-27 09:54 UTC, matteoKuama commented on app/src/main/java/net/kuama/documentscanner/presentation/PaperRect.kt
>  //        corners.log()
remove commented code

2022-07-27 09:57 UTC, GabM3 requested changes

2022-07-27 09:57 UTC, GabM3 commented on app/src/main/java/net/kuama/documentscanner/extensions/View.kt
> +    viewTreeObserver.addOnGlobalLayoutListener(object : OnGlobalLayoutListener {
```suggestion
   viewTreeObserver.addOnGlobalLayoutListener(object : OnGlobalLayoutListener {
```

2022-07-27 09:57 UTC, GabM3 commented on app/src/main/java/net/kuama/documentscanner/presentation/PaperRect.kt
>  //        corners.log()
```suggestion
```

2022-07-27 09:57 UTC, GabM3 commented on app/src/main/java/net/kuama/documentscanner/presentation/PaperRect.kt
>  //        corners.log()
```suggestion
```

2022-07-27 09:57 UTC, GabM3 commented on app/src/main/java/net/kuama/documentscanner/viewmodels/CropperModel.kt
> +                        corners.value = pair.corners
```suggestion
                        corners.value = it
```

2022-07-27 09:57 UTC, GabM3 commented on settings.gradle
> +include ":app"
go back to previous settings, it is still a dependency

2022-07-27 10:06 UTC, SimoneBressan requested changes

2022-07-27 10:06 UTC, SimoneBressan commented on app/src/main/java/net/kuama/documentscanner/viewmodels/CropperModel.kt
> +    }
Delete or add TODO

2022-07-27 10:06 UTC, SimoneBressan commented on app/src/main/java/net/kuama/documentscanner/utils/PerspectiveTransformUtils.kt
> +    fun sortPoints(sourcePointsArray: Array<Point>): Array<Point> {
Create a Square class

2022-07-27 10:06 UTC, SimoneBressan commented on app/src/main/java/net/kuama/documentscanner/extensions/Context.kt
> +        val mediaDir = filesDir.let {
Maybe let is not required

2022-07-27 10:06 UTC, SimoneBressan commented on app/src/main/java/net/kuama/documentscanner/data/Corners.kt
> +    val topLeft: Point = points[0]
Not need size
Maybe Square, Rectangle, Rect

2022-07-27 10:06 UTC, SimoneBressan commented on app/src/main/java/net/kuama/documentscanner/presentation/PaperRect.kt
> +        bl = corners.bottomLeft
Delete a cornsers.log();
Merge a points in a single variable "Cornsers"

2022-07-27 10:06 UTC, SimoneBressan commented on app/src/main/java/net/kuama/documentscanner/presentation/ScannerActivity.kt
> +            is NullCornersException -> Toast.makeText(
NotExitSquareException
MissingSquareException

2022-07-27 15:01 UTC, GabM3 commented
I can't mark the conversations are solved, can anyone do it?

2022-07-28 08:03 UTC, giovanni-nic-kuama commented on app/src/main/java/net/kuama/documentscanner/viewmodels/CropperModel.kt
> +    }
Devo capire come gestire sta cosa. Non posso eliminare perchè l'uso dell'Either mi obbliga a gestirlo questo caso.

2022-07-28 08:30 UTC, SimoneBressan approved these changes

2022-07-28 08:42 UTC, matteoKuama approved these changes

2022-07-28 08:53 UTC, matteoKuama approved these changes

2022-07-28 09:47 UTC, merged