fix (CropperActivity) sort corners after the user modified their position
Kuama-IT/android-document-scanner pull request #25
Opened 2022-08-04 15:03 UTC by giovanni-nic-kuama

fix (BaseScannerActivity) manage device orientation togheter to Bitmap orientation

2022-08-04 15:27 UTC, GabM3 requested changes

2022-08-04 15:27 UTC, GabM3 commented on app/src/main/java/net/kuama/documentscanner/viewmodels/CropperModel.kt
> +                    result.fold(::handleFailure) { bitmap ->
```suggestion
                ) {  
                    it.fold(::handleFailure) { bitmap ->
```

2022-08-05 07:28 UTC, GabM3 submitted a review, later dismissed

2022-08-05 08:38 UTC, matteoKuama requested changes

2022-08-05 08:38 UTC, matteoKuama commented on app/src/main/java/net/kuama/documentscanner/presentation/CropperActivity.kt
> +    private var screenOrientationDeg: Int? = 0
```suggestion
    private var screenOrientationDeg: Int = 0
```
or
```suggestion
    private var screenOrientationDeg: Int?
```
choose nullable or with default value

2022-08-05 08:38 UTC, matteoKuama commented on app/src/main/java/net/kuama/documentscanner/viewmodels/CropperModel.kt
> +    fun onViewCreated(uri: Uri, screenOrientationDeg: Int?, contentResolver: ContentResolver) {
if you choose to have a default value
```suggestion
    fun onViewCreated(uri: Uri, screenOrientationDeg: Int, contentResolver: ContentResolver) {
```

2022-08-05 08:38 UTC, matteoKuama commented on app/src/main/java/net/kuama/documentscanner/viewmodels/CropperModel.kt
> +                acceptedCorners.bottomRight, acceptedCorners.bottomLeft)
```suggestion
            val acceptedAndOrderedCorners = listOf(acceptedCorners.topLeft,
                                                                              acceptedCorners.topRight,
                                                                              acceptedCorners.bottomRight, 
                                                                              acceptedCorners.bottomLeft,
                                                                             )
```
format ?

2022-08-05 08:38 UTC, matteoKuama commented on app/src/main/java/net/kuama/documentscanner/presentation/BaseScannerActivity.kt
> +                    in 45 until 135 -> 270
```suggestion
               val rotationDegree = when (orientation) {
                    ORIENTATION_UNKNOWN -> return
                    in 45 until 135 -> 270
```

2022-08-05 10:52 UTC, matteoKuama reviewed
rebase

2022-08-05 10:56 UTC, matteoKuama approved these changes

2022-08-05 10:56 UTC, merged